#!/bin/bash

#set NODE_ENV = production
export NODE_ENV='production'

#set ulimit
ulimit -c unlimited

#source ~/.nvm/nvm.sh
#nvm use v0.11.16

cd `dirname $0`
NODEJS='node --harmony'
BASE_HOME=`pwd`
PROJECT_NAME=`basename ${BASE_HOME}`
STDOUT_LOG=${BASE_HOME}/logs/start.log
NODE_DISPATH_PATH=${BASE_HOME}/start.js
PROG_NAME=$0
ACTION=$1
usage() {
  echo "Usage: $PROG_NAME {start|stop|status|restart}"
  exit 1;
}

if [ $# -lt 1 ]; then
  usage
fi

function get_pid {
  PID=`ps ax | grep node | grep ${PROJECT_NAME}/start.js | awk '{print $1}'`
}

#start nodejs
start()
{
   get_pid
   if [ -z $PID ]; then
      echo "正在启动 $PROJECT_NAME ..."
      echo "nohup $NODEJS $NODE_DISPATH_PATH >> $STDOUT_LOG 2>&1 &"
      nohup $NODEJS $NODE_DISPATH_PATH >> $STDOUT_LOG  2>&1 &
      sleep 2
      get_pid
      echo "$PROJECT_NAME 启动成功。PID=$PID"
   else
      echo "$PROJECT_NAME 正在运行，PID=$PID"
   fi
}

stop()
{
  get_pid
  if [ ! -z "$PID" ]; then
    echo "2s 后停止 $PROJECT_NAME ..."
    kill -15 $PID
    sleep 2

    node_num=`ps -ef |grep node|grep ${PROJECT_NAME}|grep -v grep|wc -l`
    if [ $node_num != 0 ]; then
      ps -ef |grep node | grep ${PROJECT_NAME} |grep -v grep|awk '{print $2}'|xargs kill -9
      ipcs -s | grep 0x | awk '{print $2}' | xargs -n1 ipcrm -s  > /dev/null 2>&1
      ipcs -m | grep 0x | awk '{print $2}' | xargs -n1 ipcrm -m  > /dev/null 2>&1
    fi
  else
    echo "$PROJECT_NAME 未启动！"
  fi
}

status()
{
  get_pid
  if [ ! -z $PID ]; then
    echo "$PROJECT_NAME PID: $PID"
    node_processes=`ps -ef | grep $PID | grep -v grep`
    echo "master:"
    echo "$node_processes" | grep start.js
    worker_count=`echo "$node_processes" | grep -v start.js | wc -l`
    echo "workers: $worker_count"
    echo "$node_processes" | grep -v start.js
  else
    echo "$PROJECT_NAME 未启动！"
  fi
  exit 0;
}

case "$ACTION" in
  start)
    start
  ;;
  status)
    status
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    start
  ;;
  *)
    usage
  ;;
esac
